name: Setup Maven
description: This action sets up ./mvnw for Maven

inputs:
  java_distribution:
    description: Java distribution method
    default: 'zulu'
  java_version:
    description: Java major version number (eg, 8)
    default: '8'
  java_cache:
    description: Java cache type (eg, Maven, Gradle, etc)
    default: 'maven'

runs:
  using: composite
  steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
        cache: ${{ inputs.java_cache }}

    - name: File System preparation
      shell: bash
      run: chmod 755 mvnw
