# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test Auto-Update Dependencies for Develop

on:
  workflow_dispatch:
  schedule:
    - cron: '0,10,20,30,40,50 9-17 * * 1-5'

jobs:
  # This job checks the last commit in Develop's timestamp.  If greater than 24 hours old, this will fail.
  # This is to prevent unnecessary duplicate nightly builds.
  Check_Last_Commit_Date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.result.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: Print latest_commit
        run: echo ${{ github.sha }}

      - name: Check latest commit is less than a day
        continue-on-error: true
        if: ${{ github.event_name == 'schedule' }}
        # run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
        run: test -z $(git rev-list --after="10 minutes" ${{ github.sha }}) && echo "should_run=false" || echo "should_run=true" >> $GITHUB_ENV

      - name: Manually triggered build, always run
        if: ${{ github.event_name != 'schedule' }}
        run: echo "should_run=true" >> $GITHUB_ENV

      - name: Print result
        id: result
        run: echo "::set-output name=should_run::${{ env.should_run }}"

  Nightly_Bridge_Build:
    # Do not run if there has been no commits since last
    needs: Check_Last_Commit_Date
    if: ${{ needs.Check_Last_Commit_Date.outputs.should_run == 'true' }}
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.JW_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        os: ['windows']
        jdk: [ '1.8' ]

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Clone the source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.JW_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-

      - name: update API version
        run: |
          mvn versions:update-properties@update-properties-latest -U
          $POM_CHANGED=git status --porcelain
          echo "update-properties completed-------------------"
          if ( $POM_CHANGED -like '*pom.xml*' )
          {
            echo "code_changed=$POM_CHANGED" >> $env:GITHUB_ENV            
          }

      - name: Create Auto-Version Branch from Develop
        if: ${{ env.code_changed }}
        run: |
          git switch develop
          git checkout -b feature/auto-version-${{ github.run_number }}

      - name: Commit POM changes
        if: ${{ env.code_changed }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./pom.xml
          git commit -m 'POM versions changed'
          git push --set-upstream origin feature/auto-version-${{ github.run_number }}

      # See: https://cli.github.com/manual/
      - name: Create pull request for Auto-Version into Develop
        if: ${{ env.code_changed }}
        run: >
          gh pr create
          --base develop
          --head feature/auto-version-${{ github.run_number }}
          --title "$(date +'%m-%d-%Y') - Maven POM auto updates into Develop"
          --body "Created by Scheduled GitHub action"