# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build for Develop/Support/Hotfix branch

on:
  pull_request:
    branches:
      - develop
      - support/**
      - hotfix/**
    types: [ closed ]

jobs:
  validate_name:
    runs-on: ubuntu-latest
    steps:
      - name: get jira name
        id: branch
        run: |
          if [[ ${GITHUB_REF#refs/heads/} == @(develop|master) ]]; then
           echo ::set-output name=jira::$(echo ${GITHUB_REF} |cut -d'/' -f3 | cut -d '-' -f1,2)  
          else
           echo ::set-output name=jira::$(echo ${GITHUB_REF} |cut -d'/' -f4 | cut -d '-' -f1,2)
          fi
      - name: jira Name from upper case to lower case
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ steps.branch.outputs.jira }}
    outputs:
      jira_name: ${{ steps.string.outputs.lowercase }}

  Build_FizzBuzz:
    needs: validate_name
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        os: ['windows']
        jdk: [ '1.8' ]

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Clone the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-

      - name: Get latest tag
        id: get-latest-tag
        run: |
          $TAG=git describe --tags --abbrev=0
          echo "version-tag=$TAG" >> $env:GITHUB_ENV

      # Get next semantic build tag number
      - name: Get version
        id: calc-next-version
        run: |
          $MAJOR=mvn build-helper:parse-version -D"version.version"=${{ env.version-tag }} help:evaluate -Dexpression="parsedVersion.majorVersion" -q -DforceStdout
          $MINOR=mvn build-helper:parse-version -D"version.version"=${{ env.version-tag }} help:evaluate -Dexpression="parsedVersion.minorVersion" -q -DforceStdout
          $INCREMENT=mvn build-helper:parse-version -D"version.version"=${{ env.version-tag }} help:evaluate -Dexpression="parsedVersion.nextIncrementalVersion" -q -DforceStdout
          $NEXT_SEMANTIC_TAG=$MAJOR+'.'+$MINOR+'.'+$INCREMENT
          echo "version=$NEXT_SEMANTIC_TAG" >> $env:GITHUB_ENV

      # Get the current semantic build tag for the branch i.e excluding '-s' or '-d'
      - name: Get current build number
        id: get-current-version
        run: |
          $MAJOR=mvn build-helper:parse-version -D"version.version"=${{ env.version-tag }} help:evaluate -Dexpression="parsedVersion.majorVersion" -q -DforceStdout
          $MINOR=mvn build-helper:parse-version -D"version.version"=${{ env.version-tag }} help:evaluate -Dexpression="parsedVersion.minorVersion" -q -DforceStdout
          $BUILDNUMBER=mvn build-helper:parse-version -D"version.version"=${{ env.version-tag }} help:evaluate -Dexpression="parsedVersion.incrementalVersion" -q -DforceStdout
          $CURRENT_VERSION=$MAJOR+'.'+$MINOR+'.'+$BUILDNUMBER
          if ( ${{ github.event.pull_request.merged == true && github.base_ref == 'develop' && startsWith(github.head_ref, 'feature/') }} ) {
          $CURRENT_VERSION=$CURRENT_VERSION-d${{ github.run_number }} }
          elseif ( ${{ github.event.pull_request.merged == true  && startsWith(github.base_ref, 'support/') && startsWith(github.head_ref, 'feature/') }} ) {
          $CURRENT_VERSION=$CURRENT_VERSION-s${{ github.run_number }} }
          elseif ( ${{ github.event.pull_request.merged == true  && startsWith(github.base_ref, 'hotfix/') && startsWith(github.head_ref, 'feature/') }} ) {
          $CURRENT_VERSION=$CURRENT_VERSION-h${{ github.run_number }} }
          else { exit 0 }
          echo "currentVersion=$CURRENT_VERSION" >> $env:GITHUB_ENV

      # Print the branch names which is worked on
      - name: Print branch names
        run: |
          echo "Branch name is: ${{ github.base_ref }}"
          echo "HEAD branch is: ${{ github.head_ref }}"

      # Build and tag develop branch with '-d'
      - name: Build with Maven - ${{ env.currentVersion }}
        run: |
          echo "Version will be ${{ env.currentVersion }}"
          echo "tag is ${{ env.version-tag }}"
          mvn versions:set -DnewVersion="${{ env.currentVersion }}"
          mvn --batch-mode clean install

      - name: Tag the code
        id: tag_version_develop
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.currentVersion }}
          tag_prefix: ''