# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Bump Develop version after merge to Master

# Purpose: This will bump the project.version of Develop's pom.xml by 1 minor version after being merged into Master via Pull Request.
# Steps:
# 1. Checkout Master.
# 2. Get the current project.version from the pom.xml in Master.
# 3. Increase the Minor version of Develop by 1.  Reset Patch version to 0.  Change Qualifier to -SNAPSHOT.
# 4. Set the project.version and commit the pom.xml change to Develop.
# 5. Create a pull request to bump the version number and to merge any changes that might have been done in release/**.

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  Increment_Develop:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.base_ref == 'master'
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        os: ['linux']
        jdk: [ '1.8' ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-

      - name: Calculate next version
        run: |
          export current=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
          export major=`mvn build-helper:parse-version -Dversion.version="${current}" help:evaluate -Dexpression=parsedVersion.majorVersion -q -DforceStdout`
          export minor=`mvn build-helper:parse-version -Dversion.version="${current}" help:evaluate -Dexpression=parsedVersion.nextMinorVersion -q -DforceStdout`
          export nextVersion="${major}.${minor}.0-SNAPSHOT"
          echo "Current version is ${current}"
          echo "Develop will be bumped to ${nextVersion}"
          echo "nextVersion=${nextVersion}" >> $GITHUB_ENV

      - name: Create bump Feature Branch from Master
        run: |
          git checkout -b feature/${{ env.nextVersion }}
          git push --set-upstream origin feature/${{ env.nextVersion }}

      - name: Bump Develop version to ${{ env.nextVersion }}
        run: |
          mvn versions:set -DnewVersion=${{ env.nextVersion }} versions:commit
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "POM Develop bumped to ${{ env.nextVersion }}"
          git pull
          git push

      # See: https://cli.github.com/manual/
      - name: Create pull request to Bump version in Develop
        run: >
          gh pr create
          --base develop
          --head feature/${{ env.nextVersion }}
          --title "Bump Develop to ${{ env.nextVersion }}"
          --body "Merge all possible changes from Release branch.  Also bump the Develop branch version to ${{ env.nextVersion }}.  This is an automated Pull Request created by GitHub action."