# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Bump Develop version after merge to Master

# Increment the Develop minor version after it is merged to Master
# Develop should be 0.1.0 (1 minor version) ahead of Master.
# Note: This workflow will only run when a Pull Request from Develop is CLOSED and MERGED to Master.

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  Increment_Develop:
    if: github.event.pull_request.merged == true && github.head_ref == 'develop' && github.base_ref == 'master'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: ['linux']
        jdk: [ '1.8' ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-

      - name: Calculate next version
        id: calc-next-version
        run: |
          export current=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
          export major=`mvn build-helper:parse-version -Dversion.version="${current}" help:evaluate -Dexpression=parsedVersion.majorVersion -q -DforceStdout`
          export minor=`mvn build-helper:parse-version -Dversion.version="${current}" help:evaluate -Dexpression=parsedVersion.nextMinorVersion -q -DforceStdout`
          export nextVersion="${major}.${minor}.0-SNAPSHOT"
          echo "Current version is ${current}"
          echo "Develop will be bumped to ${nextVersion}"
          echo "::set-output name=nextVersion::${nextVersion}"

      - name: Bump Develop version to ${{ steps.calc-next-version.outputs.nextVersion }}
        run: |
          mvn versions:set -DnewVersion=${{ steps.calc-next-version.outputs.nextVersion }} versions:commit
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "POM Develop bumped to ${{ steps.calc-next-version.outputs.nextVersion }}"
          git pull
          git push