# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build for Release branch
on:
  push:
    branches:
      - release/**

jobs:
  validate_name:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version name
        id: branch
        run: |
          if [[ ${GITHUB_REF#refs/heads/} == @(develop|main) ]]; then
           echo ::set-output name=release::$(echo ${GITHUB_REF} |cut -d'/' -f3 | cut -d '-' -f1,2)  
          else
           echo ::set-output name=release::$(echo ${GITHUB_REF} |cut -d'/' -f4 | cut -d '-' -f1,2)
          fi
      - name: Release version name from upper case to lower case
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ steps.branch.outputs.release }}
    outputs:
      jira_name: ${{ steps.string.outputs.lowercase }}

  Build_Bridge:
    needs: validate_name
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        os: ['windows']
        jdk: [ '1.8' ]

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Clone the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-

      - name: Set up cache for NSIS v2.46
        id: cache_NSIS
        uses: actions/cache@v2
        with:
          path: C:\Program Files (x86)\NSIS
          key: ${{ matrix.os }}-nsis

      # $CURRENT_PROJECT_VERSION is commit pushed into Release.
      # Version numbers are in <Major>.<Minor>.<Patch> format.  $MAJOR, $MINOR, and $PATCH are those respective numbers.
      # $RELEASE_VERSION should be $CURRENT_PROJECT_VERSION without the possible $QUALIFIER, eg "1.0.245-d20220513_1553.abcdef" would be "1.0.245".
      # $RELEASE_BUILD should be $CURRENT_PROJECT_VERSION with a new $QUALIFIER of '-r[Date/Time create].[commit]'
      - name: Calculate Release Version
        run: |
          $CURRENT_PROJECT_VERSION=mvn help:evaluate -Dexpression="project.version" -q -DforceStdout
          $MAJOR=mvn build-helper:parse-version -D"version.version"=$CURRENT_PROJECT_VERSION help:evaluate -Dexpression="parsedVersion.majorVersion" -q -DforceStdout
          $MINOR=mvn build-helper:parse-version -D"version.version"=$CURRENT_PROJECT_VERSION help:evaluate -Dexpression="parsedVersion.minorVersion" -q -DforceStdout
          $PATCH=mvn build-helper:parse-version -D"version.version"=$CURRENT_PROJECT_VERSION help:evaluate -Dexpression="parsedVersion.buildNumber" -q -DforceStdout
          $RELEASE_VERSION=$MAJOR+'.'+$MINOR+'.'+$PATCH
          $RELEASE_BUILD=$RELEASE_VERSION+'-r'+$(date +'%Y%m%d')+'.'+$(git rev-parse --short HEAD)
          echo "Version of push being merged into Release is $CURRENT_PROJECT_VERSION"
          echo "Release branch will be tagged $RELEASE_VERSION after completion."
          echo "Release build will be $RELEASE_BUILD after completion."
          echo "Release_Version=$RELEASE_VERSION" >> $env:GITHUB_ENV
          echo "Release_Build=$RELEASE_BUILD" >> $env:GITHUB_ENV

      # Build Release branch
      - name: Build Release ${{ env.Release_Build }} with Maven
        # FIXME: Change this from install to deploy.
        # Update version.txt file to allow users to quickly determine Bridge version.
        #          echo "${{ steps.calculate_release_version.outputs.release-version }}" > bridge-backend/meditechConfig/version.txt
        run: |
          mvn versions:set -DnewVersion="${{ env.Release_Build }}" versions:commit
          mvn --batch-mode clean install

      # Required for Bridge to build *.exe installer
      - name: Install NSIS if not cached
        if: steps.cache_NSIS.outputs.cache-hit != 'true'
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
          choco install nsis.install --version=2.46 -y -dv

      # This step overwrites parts of the NSIS program with PK specific code.  I don't know what exactly.
      #      - name: Extract NSIS log if not cached
      #        if: steps.cache_NSIS.outputs.cache-hit != 'true'
      #        run: |
      #          echo "$(pwd)"
      #          7z.exe x "D:\a\pk-bridge\pk-bridge\bridge-build\nsis-2.46-log.zip" -o"C:\Program Files (x86)\NSIS" -y -r
      #          cd "D:\a\pk-bridge\pk-bridge"
      #          echo "$(pwd)"
      #          dir

      # Create Bridge.zip and Bridge.exe
      #      - name: Create Bridge installer
      #        run: |
      #          & 'C:\Program Files (x86)\NSIS\makensis.exe' /DMIM_FILENAME="D:\a\pk-bridge\pk-bridge\bridge-build\bridge.zip" /DVERSION_NUMBER="${{ env.Release_Build }}" /DPRODUCT_VERSION="${{ env.Release_Build }}" "D:\a\pk-bridge\pk-bridge\installer\bridge\bridge.nsi"

      # Copy zip and exe files to staging. Add version number to .exe file.
      # Then upload them to GitHub via deploy.
      #      - name: Copy and Upload Bridge zip, exe, and setupexe via Maven
      #        run: |
      #          mkdir staging
      #          copy "D:/a/pk-bridge/pk-bridge/bridge-build/*.zip" staging
      #          copy "D:/a/pk-bridge/pk-bridge/installer/bridge/*.exe" staging
      #          copy "D:\a\pk-bridge\pk-bridge\installer\bridge\bridgesetup-${{ env.Release_Build }}.exe" "D:\a\pk-bridge\pk-bridge\staging\bridge.exe"
      #          ./mvnw --batch-mode -f "uploadzip.xml" clean deploy -Drevision="${{ env.Release_Build }}" -s .mvn/wrapper/settings.xml
      #          ./mvnw --batch-mode -f "uploadexe.xml" clean deploy -Drevision="${{ env.Release_Build }}" -s .mvn/wrapper/settings.xml
      #          ./mvnw --batch-mode -f "uploadsetupexe.xml" clean deploy -Drevision="${{ env.Release_Build }}" -s .mvn/wrapper/settings.xml